version: 2
sources:
    name: Project_Prod
    database: DBT_DB
    schema: PROD
    tables:
      name: employee
      freshness: 
          warn_after: {count: 10, period: minute}
          error_after: {count: 20, period: minute}
      loaded_at_field: Created_DT